### ISSUE TITLE
User

### ISSUE THREAD

**Issue by Evajuliab** [codewtt/cat-eshop#2]
## Why ?

Pour permettre à un utilisateur de gérer son compte

## Must have
Un compte utilisateur fonctionnel avec système d'authentification 

## to-dos 
- [ ] Installer devise avec le modèle user et les views
- [ ] Page login et signup
- [ ] Page profil user avec edit des infos
